### ISSUE TITLE
Guice error running application on generated jar

### ISSUE THREAD

**Issue by rodricifuentes1** [racc/typesafeconfig-guice#4]
Hello Jason, 

I'm using your library in my project and is working as expected but I have a little problem.
When I try to run my application as a stand-alone jar I'm getting this error.

``` java
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.lang.Integer annotated with @com.github.racc.tscg.TypesafeConfig(value=server.instances) was bound.
  while locating java.lang.Integer annotated with @com.github.racc.tscg.TypesafeConfig(value=server.instances)
    for parameter 2 at com.myapp.infrastructure.conf.ServerConfig.<init>(ServerConfig.java:15)
  at com.myapp.infrastructure.CommonModule.configure(CommonModule.java:29)

2) No implementation for java.lang.Integer annotated with @com.github.racc.tscg.TypesafeConfig(value=server.port) was bound.
  while locating java.lang.Integer annotated with @com.github.racc.tscg.TypesafeConfig(value=server.port)
    for parameter 1 at com.myapp.infrastructure.conf.ServerConfig.<init>(ServerConfig.java:15)
  at com.myapp.infrastructure.CommonModule.configure(CommonModule.java:29)

3) No implementation for java.lang.String annotated with @com.github.racc.tscg.TypesafeConfig(value=amadeus.url) was bound.
  while locating java.lang.String annotated with @com.github.racc.tscg.TypesafeConfig(value=amadeus.url)
    for parameter 1 at com.myapp.infrastructure.conf.AmadeusConfig.<init>(AmadeusConfig.java:13)
  at com.myapp.infrastructure.CommonModule.configure(CommonModule.java:28)

4) No implementation for java.lang.String annotated with @com.github.racc.tscg.TypesafeConfig(value=amadeus.wsdl) was bound.
  while locating java.lang.String annotated with @com.github.racc.tscg.TypesafeConfig(value=amadeus.wsdl)
    for parameter 0 at com.myapp.infrastructure.conf.AmadeusConfig.<init>(AmadeusConfig.java:13)
  at com.myapp.infrastructure.CommonModule.configure(CommonModule.java:28)

5) No implementation for java.lang.String annotated with @com.github.racc.tscg.TypesafeConfig(value=server.host) was bound.
  while locating java.lang.String annotated with @com.github.racc.tscg.TypesafeConfig(value=server.host)
    for parameter 0 at com.myapp.infrastructure.conf.ServerConfig.<init>(ServerConfig.java:15)
  at com.myapp.infrastructure.CommonModule.configure(CommonModule.java:29)

6) No implementation for com.myapp.infrastructure.conf.hystrix.AbstractCommandConfig annotated with @com.github.racc.tscg.TypesafeConfig(value=hystrix.default.command) was bound.
  while locating com.myapp.infrastructure.conf.hystrix.AbstractCommandConfig annotated with @com.github.racc.tscg.TypesafeConfig(value=hystrix.default.command)
    for field at com.myapp.infrastructure.conf.hystrix.DefaultHystrixCommandConfig.commandConfig(DefaultHystrixCommandConfig.java:9)
  at com.myapp.infrastructure.CommonModule.configure(CommonModule.java:32)

7) No implementation for com.myapp.infrastructure.conf.hystrix.AbstractThreadPoolConfig annotated with @com.github.racc.tscg.TypesafeConfig(value=hystrix.default.threadPool) was bound.
  while locating com.myapp.infrastructure.conf.hystrix.AbstractThreadPoolConfig annotated with @com.github.racc.tscg.TypesafeConfig(value=hystrix.default.threadPool)
    for field at com.myapp.infrastructure.conf.hystrix.DefaultHystrixCommandConfig.threadPoolConfig(DefaultHystrixCommandConfig.java:9)
  at com.myapp.infrastructure.CommonModule.configure(CommonModule.java:32)
```

The extrange thing is that I have not problems when I run my application with gradle using `gradle run` command.
Here is one example of my configuration classes:

``` java
package com.copaair.connectmiles.infrastructure.conf;

import com.github.racc.tscg.TypesafeConfig;
import com.google.inject.Inject;

public class ServerConfig {

    private final String host;
    private final int port;
    private final int instances;

    @Inject
    public ServerConfig(@TypesafeConfig("server.host") String host,
                        @TypesafeConfig("server.port") int port,
                        @TypesafeConfig("server.instances") int instances) {
        this.host = host;
        this.port = port;
        this.instances = instances;
    }

    public String getHost() {
        return host;
    }

    public int getPort() {
        return port;
    }

    public int getInstances() {
        return instances;
    }
}
```

What am I missing?
Thank you very much!!!

**Comment by racc** [comment]
How do you instantiate the TypesafeConfigModule?
Have you tried `TypesafeConfigModule.fromConfigWithPackage(config, "com.myapp")`?

**Comment by rodricifuentes1** [comment]
Yes. As I said, running it with grade works perfectly, but something happens when I build the fat jar using shadowjar. This issue is similar to [this one](https://github.com/racc/typesafeconfig-guice/issues/2).

**Comment by racc** [comment]
Yes I did think that issue was similar. I'll do some testing with the shadowjar plugin and get back to you. At the moment, I've done a test by building a distribution zip using the `gradle distZip` command (along with the application plugin) and it seems to work ok.

**Comment by racc** [comment]
I couldn't replicate the problem, sorry.
I've made a test project here for your reference to try to replicate the issue using shadowjar: https://github.com/racc/typesafeconfig-guice-test

When I run the `gradle shadowJar` task, and run my Test-all.jar file, it works.

**Comment by rodricifuentes1** [comment]
Thank you for your help.
I'll work through this issue later, if I find a solution I'll write you what is happening.
Regards!

**Comment by fayimora** [comment]
Was unable to resolve this issue too. I'll be taking another look soon and will update #2 if I figure it out

**Comment by fayimora** [comment]
@rodricifuentes1 were you able to resolve this?

**Comment by rodricifuentes1** [comment]
@fayimora Nope, I didn't have time to keep looking for a solution :(

**Comment by racc** [comment]
did you look at my example project? 
https://github.com/racc/typesafeconfig-guice-test

**Comment by zhangpp520** [comment]
@racc
I met the same situation of this issue and I tried https://github.com/racc/typesafeconfig-guice-test.
It works!
But I found if I wrote this way:

```
public class Main {
    @Inject
    private Injectable injectable;
    public Main() {
        Config config = ConfigFactory.load();
        System.out.println(config.getString("test.prop"));
        System.out.println(config.getString("test.prop2"));

        Injector injector = Guice.createInjector(TypesafeConfigModule.fromConfig(config));
        injector.injectMembers(this);
        System.out.println(injectable);
    }

    public static void main(String[] args) {
        Main main = new Main();
    }
}
```

It will replicate the issue!

**Comment by racc** [comment]
The use of the method TypesafeConfigModule.fromConfig(config) is now deprecated as of the latest version (0.0.3).
Using TypesafeConfigModule.fromConfigWithPackage(config, packagePrefix) is now the preferred way of instantiating the TypesafeConfigModule - you should specify a package prefix for classes to scan.
